name: Create Release
on:
  push:
    branches:
      - master

jobs:
  createRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Release
        id: createRelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.IX_ACTIONS_PAT }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Feature to Sync dependabot secrets
          draft: false
          prerelease: false
